# Generated by Django 3.1.5 on 2021-10-15 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleader',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='name',
            field=models.CharField(default='tl name', max_length=150),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project'),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='ssdc_number',
            field=models.CharField(default='tl ssdc number', max_length=100),
        ),
    ]
